{{- $secret := false}}
{{- range $index, $connectorWithCustomTemplate := .Values.connectorsWithCustomTemplates }}
{{- if $connectorWithCustomTemplate.webhook_url }}
{{- $secret = true}}
{{- end}}
{{- end}}

{{- if $secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "app.name" . }}-secret
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  {{- range $index, $connectorWithCustomTemplate := .Values.connectorsWithCustomTemplates }}
    {{- if $connectorWithCustomTemplate.webhook_url }}
  {{ $connectorWithCustomTemplate.name | upper }}_SECRET_VAR: {{ $connectorWithCustomTemplate.webhook_url | b64enc}}
    {{- end}}
  {{- end}}
{{- end}}